### PR TITLE
Add prounouns field instead of determining pronouns from gender field.

### LINKED ISSUE #129: Ensure equity and inclusion with gender pronoun property for Person class
While the gender property is derived from the foaf specification which seems inclusive in its explanation of how gender should be dealt with:
http://xmlns.com/foaf/spec/#term_gender

deriving pronouns from a gender property is becoming increasingly insufficient for inclusion and equity, especially for democratic standards that are aiming for these values:

https://www.popoloproject.com/specs/person.html:
```
gender

    To determine personal pronouns, e.g. “John Doe will be at his constituency office next week.”
```

An additional property to specify personal pronouns is probably a step in the right direction.

For more information on what this means and why it's important, see the FOAF specification mentioned earlier or maybe these:

https://www.hrc.org/resources/talking-about-pronouns-in-the-workplace

and

https://assets2.hrc.org/files/assets/resources/TalkingAboutPronouns_onesheet_FINAL.pdf

### PR DESCRIPTION
**Pull request by geekpete**
Don't use gender field to determine personal pronouns, use pronouns field instead.
Fixes: https://github.com/popolo-project/popolo-spec/issues/129

### CODE REVIEW

**Comment by geekpete** [comment]
@jpmckinney wondering if this is was all that's needed for https://github.com/popolo-project/popolo-spec/issues/129

**Review by jpmckinney — COMMENTED** [review]
`pronouns` probably needs to be an array of strings. Also, can you not re-number the list? `1.` works in Markdown to auto-increment when rendered.

**Comment by geekpete** [comment]
Let me know if this addresses the issues described. I set to array, was there a way to specify an array only of strings?

**Comment by jpmckinney** [comment]
Your PR is not editable so this PR is replaced by #133.

**Pull request closed without merging**
